services:
  postgres:
    container_name: fghtfrms-hktn-db
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
